import 'package:hive_flutter/hive_flutter.dart';
import '../models/attendance_model.dart';
import '../models/student_model.dart';
import '../models/subject_model.dart';
import '../models/qr_session_model.dart';

class StorageService {
  static const String attendanceBoxName = 'attendance';
  static const String studentBoxName = 'students';
  static const String subjectBoxName = 'subjects';
  static const String qrSessionBoxName = 'qr_sessions';
  static const String settingsBoxName = 'settings';

  static Future<void> init() async {
    await Hive.initFlutter();
    
    // Register adapters (will be generated by build_runner)
    // For now, we'll use type adapters manually
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(AttendanceModelAdapter());
    }
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(StudentModelAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(SubjectModelAdapter());
    }
    if (!Hive.isAdapterRegistered(3)) {
      Hive.registerAdapter(QRSessionModelAdapter());
    }

    // Open boxes
    await Hive.openBox<AttendanceModel>(attendanceBoxName);
    await Hive.openBox<StudentModel>(studentBoxName);
    await Hive.openBox<SubjectModel>(subjectBoxName);
    await Hive.openBox<QRSessionModel>(qrSessionBoxName);
    await Hive.openBox(settingsBoxName);
  }

  // Attendance methods
  static Future<void> saveAttendance(AttendanceModel attendance) async {
    final box = Hive.box<AttendanceModel>(attendanceBoxName);
    await box.put(attendance.id, attendance);
  }

  static List<AttendanceModel> getAllAttendance() {
    final box = Hive.box<AttendanceModel>(attendanceBoxName);
    return box.values.toList();
  }

  static List<AttendanceModel> getAttendanceByStudent(String studentId) {
    final box = Hive.box<AttendanceModel>(attendanceBoxName);
    return box.values.where((a) => a.studentId == studentId).toList();
  }

  static List<AttendanceModel> getAttendanceBySubject(String subjectId) {
    final box = Hive.box<AttendanceModel>(attendanceBoxName);
    return box.values.where((a) => a.subjectId == subjectId).toList();
  }

  static Future<void> deleteAttendance(String id) async {
    final box = Hive.box<AttendanceModel>(attendanceBoxName);
    await box.delete(id);
  }

  // Student methods
  static Future<void> saveStudent(StudentModel student) async {
    final box = Hive.box<StudentModel>(studentBoxName);
    await box.put(student.id, student);
  }

  static List<StudentModel> getAllStudents() {
    final box = Hive.box<StudentModel>(studentBoxName);
    return box.values.toList();
  }

  static StudentModel? getStudentById(String id) {
    final box = Hive.box<StudentModel>(studentBoxName);
    return box.get(id);
  }

  static StudentModel? getStudentByRollNumber(String rollNumber) {
    final box = Hive.box<StudentModel>(studentBoxName);
    try {
      return box.values.firstWhere((s) => s.rollNumber == rollNumber);
    } catch (e) {
      return null;
    }
  }

  static Future<void> deleteStudent(String id) async {
    final box = Hive.box<StudentModel>(studentBoxName);
    await box.delete(id);
  }

  // Subject methods
  static Future<void> saveSubject(SubjectModel subject) async {
    final box = Hive.box<SubjectModel>(subjectBoxName);
    await box.put(subject.id, subject);
  }

  static List<SubjectModel> getAllSubjects() {
    final box = Hive.box<SubjectModel>(subjectBoxName);
    return box.values.toList();
  }

  static SubjectModel? getSubjectById(String id) {
    final box = Hive.box<SubjectModel>(subjectBoxName);
    return box.get(id);
  }

  static Future<void> deleteSubject(String id) async {
    final box = Hive.box<SubjectModel>(subjectBoxName);
    await box.delete(id);
  }

  // QR Session methods
  static Future<void> saveQRSession(QRSessionModel session) async {
    final box = Hive.box<QRSessionModel>(qrSessionBoxName);
    await box.put(session.id, session);
  }

  static List<QRSessionModel> getAllQRSessions() {
    final box = Hive.box<QRSessionModel>(qrSessionBoxName);
    return box.values.toList();
  }

  static QRSessionModel? getActiveQRSession() {
    final box = Hive.box<QRSessionModel>(qrSessionBoxName);
    try {
      return box.values.firstWhere((s) => s.isActive);
    } catch (e) {
      return null;
    }
  }

  static Future<void> deactivateAllSessions() async {
    final box = Hive.box<QRSessionModel>(qrSessionBoxName);
    for (var session in box.values) {
      if (session.isActive) {
        session.isActive = false;
        session.endTime = DateTime.now();
        await session.save();
      }
    }
  }

  // Settings
  static Future<void> saveSetting(String key, dynamic value) async {
    final box = Hive.box(settingsBoxName);
    await box.put(key, value);
  }

  static dynamic getSetting(String key, {dynamic defaultValue}) {
    final box = Hive.box(settingsBoxName);
    return box.get(key, defaultValue: defaultValue);
  }
}

